# app/db/memory.py
# Database operations for conversation memory
# Handles sessions and individual messages

from app.db.database import get_connection
from datetime import datetime


def create_session(character_id: int) -> int:
    """
    Start a new play session for a character.
    Returns the new session's id.
    """
    connection = get_connection()
    cursor = connection.cursor()

    # Record when this session started
    started_at = datetime.now().isoformat()

    cursor.execute("""
        INSERT INTO sessions (character_id, started_at)
        VALUES (?, ?)
    """, (character_id, started_at))

    session_id = cursor.lastrowid
    connection.commit()
    connection.close()

    return session_id


def save_message(session_id: int, character_id: int,
                 role: str, content: str) -> None:
    """
    Save a single message to the database.

    Args:
        session_id:   Which session this belongs to
        character_id: Which character is playing
        role:         "user" or "assistant"
        content:      The actual message text
    """
    connection = get_connection()
    cursor = connection.cursor()

    created_at = datetime.now().isoformat()

    cursor.execute("""
        INSERT INTO messages (session_id, character_id, role, content, created_at)
        VALUES (?, ?, ?, ?, ?)
    """, (session_id, character_id, role, content, created_at))

    connection.commit()
    connection.close()


def get_recent_messages(character_id: int, limit: int = 20) -> list:
    """
    Get the most recent messages for a character across all sessions.
    Used to give Aldric short-term memory of recent conversation.

    Args:
        character_id: Which character to load history for
        limit:        How many messages to return

    Returns:
        List of dicts with role and content, oldest first
    """
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT role, content
        FROM messages
        WHERE character_id = ?
        ORDER BY created_at DESC
        LIMIT ?
    """, (character_id, limit))

    rows = cursor.fetchall()
    connection.close()

    # Reverse so oldest messages come first
    # (LLM needs chronological order)
    messages = [dict(row) for row in rows]
    messages.reverse()

    return messages


def get_session_messages(session_id: int) -> list:
    """
    Get all messages from one specific session.
    Used for summarization at session end.
    """
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT role, content
        FROM messages
        WHERE session_id = ?
        ORDER BY created_at ASC
    """, (session_id,))

    rows = cursor.fetchall()
    connection.close()

    return [dict(row) for row in rows]


def save_session_summary(session_id: int, summary: str) -> None:
    """
    Save a summary of what happened during a session.
    Generated by the LLM at session end.
    """
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        UPDATE sessions
        SET summary = ?
        WHERE id = ?
    """, (summary, session_id))

    connection.commit()
    connection.close()


def get_all_summaries(character_id: int) -> list:
    """
    Get summaries of all past sessions for a character.
    Used to give Aldric long-term campaign memory.

    Returns:
        List of summary strings, oldest first
    """
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT summary, started_at
        FROM sessions
        WHERE character_id = ?
        AND summary != ''
        ORDER BY started_at ASC
    """, (character_id,))

    rows = cursor.fetchall()
    connection.close()

    return [dict(row) for row in rows]